name: Run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 26

      - run: npm ci
      - run: npm run setup
      - run: npm start
        env:
          OPENGIST_URL: ${{ secrets.OPENGIST_URL }}
          OPENGIST_TOKEN: ${{ secrets.OPENGIST_TOKEN }}
          OPENGIST_GIST_ID: ${{ secrets.OPENGIST_GIST_ID }}
          DISCORD_SOURCE_TOKEN: ${{ secrets.DISCORD_SOURCE_TOKEN }}
